home/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView , LogoutView
from .views import UserUpdate , Success


urlpatterns = [
    path('', views.index , name='index'),
    path('login_success/', views.login_success, name='login_success'),
    path('test/', views.test, name='test'),
    path('doctor_list/', views.doctor_list, name='doctor_list'),
    path('doctor_home', views.doctor_home, name='doctor_home'),
    path('receptionist_home', views.receptionist_home, name='receptionist_home'),
    path('admin_home', views.admin_home, name='admin_home'),
    path('all_appointments', views.all_appointments, name='all_appointments'),
    path('register', views.UserFormView.as_view() , name='register'),
    path('doctor_register', views.DoctorFormView.as_view(), name='doctor_register'),
    path('receptionist_register', views.ReceptionistFormView.as_view(), name='receptionist_register'),
    path('login/',LoginView.as_view(template_name="home/login.html"), {'template_name': 'home/login.html'} ,name='login'),
    path('appointment/add', views.AddAppointment, name='addappointment'),
    path('appointment/<int:pk>/delete/', views.AppointmentDelete.as_view(), name='deleteappointment'),
    path('appointment/<int:pk>/', views.AppointmentUpdate.as_view(), name='updateappointment'),
    path('profile/edit/',UserUpdate.as_view(),name='user-update'),
    path('profile/edit/success', Success, name='success'),
    path('logout/',LogoutView.as_view(), {'next_page': '/index/login'}, name='logout'),
]

website/urls.py
from django.urls import path , include
from django.contrib import admin

urlpatterns = [
    path('', include(('home.urls','home'), namespace='home')),
    path('admin/', admin.site.urls),
    path('index/', include('home.urls')),
]

home/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import datetime



class Person(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    type = models.IntegerField(default=0)

    def __str__(self):
        return self.user.username

class Doctor(models.Model):
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    Speciality = models.CharField(max_length=100 , default=None)
    Address = models.CharField(max_length=100 , default=None)
    Email = models.CharField(max_length=100 , default=None)
    Phone = models.CharField(max_length=100 , default=None)
    gender = models.CharField(max_length=100 , default=None)

    def __str__(self):
        return self.person.user.username



class Receptionist(models.Model):
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    Address = models.CharField(max_length=100 , default=None)
    Email = models.CharField(max_length=100 , default=None)
    Phone = models.CharField(max_length=100 , default=None)
    gender = models.CharField(max_length=100 , default=None)

    def __str__(self):
        return self.person.user.username

class Patient(models.Model):
    person = models.OneToOneField(Person, on_delete=models.CASCADE)
    location = models.CharField(max_length=500 , blank=True , default='')
    bio = models.CharField(max_length=500, blank=True)
    Address = models.CharField(max_length=100 , default=None)
    Email = models.CharField(max_length=100 , default=None)
    Phone = models.CharField(max_length=100 , default=None)
    gender = models.CharField(max_length=100 , default=None)

    def __str__(self):
        return self.person.user.username


class Appointment(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE, null=True)
    Doctor = models.ForeignKey(Doctor , on_delete=models.CASCADE,default=None)
    Date = models.DateField(("Date"), default=datetime.date.today)
    Pending= 'PD'
    Approved= 'AP'
    Rejected = 'RJ'
    STATUS = (
        (Pending, 'Pending'),
        (Approved, 'Approved'),
        (Rejected, 'rejected'),
    )

    status = models.CharField(
        max_length=2,
        choices=STATUS,
        default=Pending,
    )

    message = models.CharField(max_length=1000 , default="Pending Approval")

    def __str__(self):
        return str(self.user)

    def get_absolute_url(self):
        return reverse('home:index')

home/forms.py
from django.contrib.auth.models import User

from django import forms
from .models import  Appointment , Patient , Person, Doctor, Receptionist


class UserForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = ('type',)


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ('Address', 'Email', 'Phone', 'gender', 'location', 'bio')


class DoctorForm(forms.ModelForm):
    class Meta:
        model = Doctor
        fields = ('Address', 'Email', 'Phone', 'gender', 'Speciality',)


class ReceptionistForm(forms.ModelForm):
    class Meta:
        model = Receptionist
        fields = ('Address', 'Email', 'Phone', 'gender',)


class AppointmentForm(forms.ModelForm):

    class Meta:
        model = Appointment
        fields = ['Doctor', 'Date']


class Login(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'password']


class UpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username',)

home/views.py
from django.shortcuts import render , redirect
from django.contrib.auth import authenticate , login , logout
from django.views.generic import View
from .models import Appointment, Person , Doctor , User , Patient, Receptionist
from django.views.generic.edit import UpdateView , DeleteView
from .forms import UserForm , PatientForm , DoctorForm , PersonForm , UpdateForm, ReceptionistForm
from django.contrib.auth.decorators import login_required
from .forms import AppointmentForm
from django.urls import reverse_lazy
from django.shortcuts import redirect


def test(request):
    return render(request, 'home/test.html')


@login_required(login_url='login')
def index(request):
    users = User.objects.all()
    appointments = Appointment.objects.filter(user=request.user)
    return render(request, 'home/index.html', {'appointments': appointments , 'Users':users})


#@login_required(login_url='login')
def doctor_list(request):
    doctors = Doctor.objects.all()
    return render(request, 'home/doctor_list.html', {'doctors': doctors})


#@login_required(login_url='login')
def doctor_home(request):
    user = request.user
    person = Person.objects.get(user=user)
    doctor = Doctor.objects.get(person=person)
    appointments = Appointment.objects.filter(Doctor=doctor)
    return render(request, 'home/doctor_home.html', {'appointments': appointments})


#@login_required(login_url='login')
def receptionist_home(request):
    user = request.user
    person = Person.objects.get(user=user)
    receptionist = Receptionist.objects.get(person=person)
    appointments = Appointment.objects.all()
    return render(request, 'home/receptionist_home.html', {'appointments': appointments})


#@login_required(login_url='login')
def admin_home(request):
    return render(request, 'home/admin_home.html')



class UserFormView(View):

    user_form_class = UserForm
    patient_form_class = PatientForm
    template_name = 'home/registration.html'

    #show blank forqm

    def get(self , request):
        u_form = self.user_form_class(None)
        p_form = self.patient_form_class(None)
        return render(request , self.template_name , {'u_form' : u_form , 'p_form' : p_form})

    #register user

    def post(self , request):
        u_form = self.user_form_class(request.POST)
        p_form = self.patient_form_class(request.POST)
        if u_form.is_valid() and p_form.is_valid():

            #save user info locally and not in the database yet
            user = u_form.save(commit=False)
            patient = p_form.save(commit=False)

            #cleaned data
            username = u_form.cleaned_data['username']
            password = u_form.cleaned_data['password']

            #can not directly update password because it is stored  as a hash value
            user.set_password(password)
            user.save()

            person = Person(user=user)

            person.save()

            #save info to DB
            patient.person = Person.objects.get(user=user)
            patient.save()

            user = authenticate(username=username , password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                return redirect('home:index')

        # if fails , then return form
        return render(request , self.template_name , {'u_form' : u_form , 'p_form' : p_form})


class DoctorFormView(View):

    user_form_class = UserForm
    doctor_form_class = DoctorForm
    person_form_class = PersonForm
    template_name = 'home/doctor_registration.html'

    #show blank forqm

    def get(self , request):
        u_form = self.user_form_class(None)
        p_form = self.person_form_class(None)
        d_form = self.doctor_form_class(None)
        return render(request , self.template_name , {'u_form' : u_form , 'p_form' : p_form,  'd_form' : d_form})

    #register user

    def post(self , request):
        u_form = self.user_form_class(request.POST)
        p_form = self.person_form_class(request.POST)
        d_form = self.doctor_form_class(request.POST)
        if u_form.is_valid() and d_form.is_valid() and p_form.is_valid():

            #save user info locally and not in the database yet
            user = u_form.save(commit=False)
            doctor = d_form.save(commit=False)
            person = p_form.save(commit=False)

            #cleaned data

            username = u_form.cleaned_data['username']
            password = u_form.cleaned_data['password']

            #can not directly update password because it is stored  as a hash value
            user.set_password(password)
            user.save()
            person.save()


            person = Person.objects.get(user=user)
            person.type=1
            person.save()


            #save info to DB
            doctor.person = Person.objects.get(user=user)
            doctor.save()
            return redirect('home:admin_home')

        # if fails , then return form
        return render(request , self.template_name , {'u_form' : u_form , 'd_form' : d_form})


class ReceptionistFormView(View):

    user_form_class = UserForm
    receptionist_form_class = ReceptionistForm
    person_form_class = PersonForm
    template_name = 'home/receptionist_registration.html'

    #show blank forqm

    def get(self , request):
        u_form = self.user_form_class(None)
        p_form = self.person_form_class(None)
        d_form = self.receptionist_form_class(None)
        return render(request , self.template_name , {'u_form' : u_form , 'p_form' : p_form,  'd_form' : d_form})

    #register user

    def post(self , request):
        u_form = self.user_form_class(request.POST)
        p_form = self.person_form_class(request.POST)
        d_form = self.receptionist_form_class(request.POST)
        if u_form.is_valid() and d_form.is_valid() and p_form.is_valid():

            #save user info locally and not in the database yet
            user = u_form.save(commit=False)
            doctor = d_form.save(commit=False)
            person = p_form.save(commit=False)

            #cleaned data

            username = u_form.cleaned_data['username']
            password = u_form.cleaned_data['password']

            #can not directly update password because it is stored  as a hash value
            user.set_password(password)
            user.save()
            person.save()


            person = Person.objects.get(user=user)
            person.type=2
            person.save()


            #save info to DB
            doctor.person = Person.objects.get(user=user)
            doctor.save()
            return redirect('home:admin_home')

        # if fails , then return form
        return render(request , self.template_name , {'u_form' : u_form , 'd_form' : d_form})


#@login_required(login_url='login')
def login_success(request):
    if request.user.is_superuser:
        return redirect("home:admin_home")
    person=Person.objects.get(user=request.user)
    if person.type == 1:
        return redirect("home:doctor_home")
    if person.type == 2:
        return redirect("home:receptionist_home")
    else:
        return redirect("home:index")


#@login_required(login_url='login')
def AddAppointment(request):
    if not request.user.is_authenticated:
        return render(request, 'index/login.html')
    else:
        form = AppointmentForm(request.POST or None)
        if form.is_valid():
            appointment = form.save(commit=False)
            appointment.user = request.user
            appointment.save()
            appointments = Appointment.objects.filter(user=request.user)
            return render(request, 'home/index.html', {'appointments': appointments})
        context = {
                "form": form,
            }
    return render(request, 'home/appointment_form.html', context)


class AppointmentDelete(DeleteView):
    model = Appointment
    success_url = reverse_lazy('home:index')


class AppointmentUpdate(UpdateView):
    model = Appointment
    fields = ['user', 'Doctor', 'Date', 'status', 'message']
    success_url = reverse_lazy('home:receptionist_home')



class UserUpdate(UpdateView):

    context_object_name = 'form'
    form_class = PatientForm
    template_name = 'home/userupdate.html'
    success_url = 'success'

    # get object
    def get_object(self, queryset=None):
        person = Person.objects.get(user=self.request.user)
        return Patient.objects.get(person=person)

    # override form_valid method
    def form_valid(self, form):
        # save cleaned post data
        clean = form.cleaned_data
        self.object = form.save(clean)
        return super(UserUpdate, self).form_valid(form)

def Success(request):
    return render(request, 'home/success.html')


def all_appointments(request):
    appointments = Appointment.objects.all()
    return render(request, 'home/all_appointments.html', {'appointments': appointments})

templates/home/admin_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Admin Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'home/welcome.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>


<body background="url('images/admin.jpg')">

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">HMS</a>
          <a class="navbar-brand" href="{% url 'home:admin_home' %}">Home</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> LogOut</a></li>
        </ul>
      </div>
    </nav>

    <p align="center" style="font-family: 'Lobster';font-size: 50px;">Welcome {{ request.user.username }}</p>
    <h2 align="center"><a href="{% url 'doctor_register' %}" > Add doctor </a></h2>
    <h2 align="center"><a href="{% url 'receptionist_register' %}" > Add Receptionist </a></h2>
    <h2 align="center"><a href='http://127.0.0.1:8000/admin' > Manage Database </a></h2>
    <h2 align="center"><a href="{% url 'all_appointments' %}" > See Appointments</a></h2>

</body>

templates/home/all_appointments.html
<!DOCTYPE html>
<html lang="en">
<head>
      <meta charset="UTF-8">
      <title>Home</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      {% load staticfiles %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'home/welcome.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>


    <div class="container-fluid text-center">
      <div class="row content">
        <div class="container">
            <!--{% if not appointments%}-->
                <!--<h2 align="left">No Appointments</h2>-->
            <!--{% else %}-->
                <h2 align="left">All Appointments</h2>
                <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Patient</th>
                        <th>Doctor</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Message</th>
                      </tr>
                    </thead>
                <tbody>
                {% for c in appointments %}
                  <tr>
                    <td>{{ c.user }}</td>
                    <td>{{ c.Doctor }}</td>
                    <td>{{ c.Date }}</td>
                    <td>{{ c.status }}</td>
                    <td>{{ c.message }}</td>
                    <td>
                      <!--<form action="{% url 'home:deleteappointment' c.id %}" method="post">{% csrf_token %}-->
                        <!--<button type="submit" class="btn btn-danger" value="Delete"> Delete </button>-->
                      <!--</form>-->
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
            <!--{% endif %}-->
          </table>
        </div>
      </div>
    </div>


</body>
</html>

templates/home/appointment_form.html
{% extends 'home/base.html' %}
{% block title %}Add your Interest{% endblock %}

{% block body %}
<h1>Doctor Appointment</h1>
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">

                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/home/base.html
<head>
      <meta charset="UTF-8">
      <title>Home</title>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'home/welcome.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">HMS</a>
          <a class="navbar-brand" href="{% url 'home:index' %}">Home</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> LogOut</a></li>
        </ul>
      </div>
    </nav>
    {% block body %}
    {% endblock %}

</body>

</html>

templates/home/doctor_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
Hey {{ request.user.username }}
</body>
</html>

templates/home/doctor_list.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
<title>Home</title>

<style>
body {
    font-family: "Lato", sans-serif;
}

.sidenav {
    height: 100%;
    width: 0;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #111;
    overflow-x: hidden;
    transition: 0.5s;
    padding-top: 60px;
}

.sidenav a {
    padding: 8px 8px 8px 32px;
    text-decoration: none;
    font-size: 25px;
    color: #818181;
    display: block;
    transition: 0.3s;
}

.sidenav a:hover {
    color: #f1f1f1;
}

.sidenav .closebtn {
    position: absolute;
    top: 0;
    right: 25px;
    font-size: 36px;
    margin-left: 50px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}
</style>
<body>

    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a href="{% url 'home:addappointment' %}">Appointments</a>
      <a href="{% url 'home:doctor_list' %}">Doctors</a>
      <a href="#">Profile</a>
    </div>

    <p style="font-family: 'Lobster';font-size: 40px;">Welcome {{ request.user.username }}</p>

    <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span>

    <script>
    function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
    }

    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }
    </script>
    <div class="container-fluid text-center">
      <div class="row content">
        <div class="container">
                <h2 align="left">Doctors</h2>
                <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Doctor</th>
                        <th>Speciality</th>
                      </tr>
                    </thead>
                <tbody>
                {% for c in doctors %}
                  <tr>
                    <td>{{ c }}</td>
                    <td>{{ c.Speciality }}</td>
                  </tr>
                {% endfor %}
                </tbody>
          </table>
        </div>
      </div>
    </div>

</body>

{% endblock %}

templates/home/form_template.html
{% for field in u_form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}


{% for field in p_form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}
{% block body %}
<title>Home</title>

<style>
body {
    font-family: "Lato", sans-serif;
}

.sidenav {
    height: 100%;
    width: 0;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #111;
    overflow-x: hidden;
    transition: 0.5s;
    padding-top: 60px;
}

.sidenav a {
    padding: 8px 8px 8px 32px;
    text-decoration: none;
    font-size: 25px;
    color: #818181;
    display: block;
    transition: 0.3s;
}

.sidenav a:hover {
    color: #f1f1f1;
}

.sidenav .closebtn {
    position: absolute;
    top: 0;
    right: 25px;
    font-size: 36px;
    margin-left: 50px;
}

@media screen and (max-height: 450px) {
  .sidenav {padding-top: 15px;}
  .sidenav a {font-size: 18px;}
}

</style>


<body>
    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a href="{% url 'home:addappointment' %}">Appointments</a>
      <a href="{% url 'home:doctor_list' %}">Doctors</a>
      <a href="{% url 'home:user-update' %}">Edit Profile</a>
    </div>

    <p style="font-family: 'Lobster';font-size: 40px;">Welcome {{ request.user.username }}</p>

    <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; Menu</span>

    <script>
    function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
    }

    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }
    </script>
    <div class="container-fluid text-center">
      <div class="row content">
        <div class="container">
            <!--{% if not appointments%}-->
                <!--<h2 align="left">No Appointments</h2>-->
            <!--{% else %}-->
                <h2 align="left">Your Appointments</h2>
                <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Doctor</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Message</th>
                      </tr>
                    </thead>
                <tbody>
                {% for c in appointments %}
                  <tr>
                    <td>{{ c.Doctor }}</td>
                    <td>{{ c.Date }}</td>
                    <td>{{ c.status }}</td>
                    <td>{{ c.message }}</td>
                    <td>
                      <form action="{% url 'home:deleteappointment' c.id %}" method="post">{% csrf_token %}
                        <button type="submit" class="btn btn-danger" value="Delete"> Delete </button>
                      </form>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
            <!--{% endif %}-->
          </table>
        </div>
      </div>
    </div>

</body>

{% endblock %}

templates/home/receptionist_home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Receptionist Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% load static %}
    <link rel="shortcut icon" type="image/png" href="{%  static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'home/welcome.css' %}"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">HMS</a>
          <a class="navbar-brand" href="{% url 'home:receptionist_home' %}">Home</a>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-out"></span> LogOut</a></li>
        </ul>
      </div>
    </nav>

    <h2> Welcome {{ request.user.username }} </h2>

     <div class="container-fluid text-center">
      <div class="row content">
        <div class="container">
                <h2 align="left">All Appointments</h2>
                <table class="table table-hover">
                    <thead>
                      <tr>
                        <th>Patient</th>
                        <th>Doctor</th>
                        <th>Date</th>
                        <th>Status</th>
                        <th>Message</th>
                      </tr>
                    </thead>
                <tbody>
                {% for c in appointments %}
                  <tr>
                    <td>{{ c.user }}</td>
                    <td>{{ c.Doctor }}</td>
                    <td>{{ c.Date }}</td>
                    <td>{{ c.status }}</td>
                    <td>{{ c.message }}</td>
                    <td>
                      <form action="{% url 'home:updateappointment' c.id %}" method="get">{% csrf_token %}
                        <button type="Submit" class="btn btn-submit" value="Update" > Update Status</button>
                      </form>
                    </td>
                  </tr>
                {% endfor %}
                </tbody>
          </table>
        </div>
      </div>
    </div>




</body>
</html>

templates/home/success.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Success</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Information Successfully Updated</h2>

  <form action="{% url 'index' %} ">
    <button type="submit" class="btn btn-primary">Go Home</button>
  </form>

</div>

</body>
</html>